name: 'Upload Pages artifact'
description: 'A composite action that prepares your static assets to be deployed to GitHub Pages'
inputs:
  directory:  # id of input
    description: 'The directory in your workspace that contains the built assets'
    required: true
    default: '_site/'
runs:
  using: "composite"
  steps:      
    - name: Archive build output
      run: "tar --dereference --hard-dereference --directory ${{ inputs.directory }} -cvf artifact.tar ."
      working-directory: "/workspace"
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: "github-pages"
        path: /workspace/artifact.tar
